### ISSUE TITLE
Language selection not possible

### ISSUE THREAD

**Issue by spooner85** [disisto/paketverfolgung.info#1]
When using the direct URLs its not possible to choose the language. 
Please make an optional language parameter available or auto-detect on browser language. 

When visiting normal Website it automatically shows it translated and the target sites (e.g. UPS is in correct language): 
https://paketverfolgung.info/DE/

**Comment by track-trace** [comment]
Hi @spooner85,

Thanks for reaching out.

So far there has been no need for a language switch for requests over one of the integrations. With the multi-language function on the website it was a simple one to adopt the feature request also for the other integrations.

Requests over the available integrations redirect **now** to a result in one of the supported languages, based on visitor's browser settings, if applicable.

There will be no parameter for a language switch for the time being, since it could possibly collided with one of the functions that will appear in one of the future versions. We will continue to consider this function as an option.

Let us know if the current implementation works for you.

Thank you,
paketverfolgung.info
